spring.application.name=sd-market-resource

spring.config.import=configserver:http://localhost:7777/

spring.cloud.openfeign.oauth2.enabled=true

#USER_RESOURCE_PREFIX=/api/users-resource

logging.level.org.springframework.security=DEBUG