spring.application.name=sd-market-resource
server.port=7071

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090

spring.cloud.openfeign.oauth2.enabled=true

spring.data.r2dbc.repositories.enabled=true
spring.r2dbc.username=postgres
spring.r2dbc.password=1234
spring.r2dbc.url=r2dbc:postgres://localhost:5432/sd_market

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql

spring.web.resources.static-locations=classpath:/,classpath:/resources/

minio.url=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=sd-market-bucket

logging.level.org.springframework.security=DEBUG